language: java

jdk: oraclejdk8

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- chmod 600 ~/.netrc

install:
- git clone https://github.com/ctlab/private-libraries.git lib
- mvn install:install-file -Dfile=lib/lib/cplex.jar -DgroupId=com.ibm -DartifactId=cplex -Dversion=12.6.3 -Dpackaging=jar

script:
- mvn -Djava.library.path=lib/lib cobertura:cobertura
- mvn install -DskipTests=true

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: target/sgmwcs-solver.jar
  skip_cleanup: true
  on:
    tags: true
